# MLHyperparameterTuning Pipeline 

trigger:
- master

variables:
- group: AzureKeyVault

jobs:
- job: MLHyperparameterTuningJob
  timeoutInMinutes: 300
  cancelTimeoutInMinutes: 2
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - bash: |
      source /usr/share/miniconda/etc/profile.d/conda.sh
      which conda
      conda env create -f environment.yml
      conda env list
      conda activate MLHyperparameterTuning
      conda env list  
      echo Login Azure Account
      az login -t $(sptenent) --service-principal -u $(spidentity) --password $(spsecret)
      az account set --subscription $(subscriptionid)
#      papermill 01_Data_Prep.ipynb 01_Data_Prep_Output.ipynb --log-output --no-progress-bar -k python3 
    displayName: 'Configuration'

  - bash: |
      source /usr/share/miniconda/etc/profile.d/conda.sh
      conda activate MLHyperparameterTuning
      az account show
    displayName: 'Subscription Test'
 