name: MLHyperparameterTuning
channels:
  - conda-forge
dependencies:
  - python=3.6
  - pip==19.2.3
  - nb_conda_kernels==2.2.2
  - pandas==0.23.4
  - scikit-learn==0.21.3
  - lightgbm==2.2.1
  - pip:
    - papermill==1.1.0
    - prompt_toolkit==2.0.9
    - azure-cli==2.0.75
    - azureml-sdk[notebooks]==1.0.69
    - git+https://github.com/Microsoft/StatisticsTracker
