name: MLBatchAIHyperparameterTuning
channels:
  - conda-forge
dependencies:
  - python=3.5
  - nb_conda==2.2.1
  - ipywidgets=7.4.0
  - tornado==4.5.3
  - pandas==0.23.4
  - scikit-learn==0.19.1
  - pip:
    - azure==4.0.0
    - azure-cli==2.0.44
    - lightgbm==2.1.2
    - papermill==0.14.2
    - git+https://github.com/theskumar/python-dotenv
