name: MLHyperparameterTuning
channels:
  - conda-forge
dependencies:
  - python=3.6
  - nb_conda_kernels==2.2.0
  - ipywidgets==7.4.2
  - pandas==0.23.4
  - scikit-learn==0.20.0
  - pip:
    - azure-cli==2.0.44
    - prompt_toolkit==2.0.7
    - azureml-sdk[notebooks]==1.0.17
    - lightgbm==2.1.2
    - papermill==0.14.2
