name: MLBatchAIHyperparameterTuning
channels:
  - conda-forge
dependencies:
  - python=3.5
  - nb_conda==2.2.1
  - pywin32==223
  - ipywidgets=7.4.0
  - tornado==4.5.3
  - pandas==0.23.4
  - pip:
    - azure-cli==2.0.44
    - scikit-learn==0.19.2
    - lightgbm==2.1.2
    - papermill==0.14.2
    - python-dotenv==0.9.1
