name: MLHyperparameterTuning
channels:
  - conda-forge
dependencies:
  - python=3.6
  - nb_conda_kernels==2.2.0
  - pandas==0.23.4
  - scikit-learn==0.20.3
  - lightgbm==2.2.1
  - pip:
    - prompt_toolkit==2.0.7
    - azure-cli==2.0.44
    - azureml-sdk[notebooks, automl]
    - papermill==0.14.2
