name: MLBatchAIHyperparameterTuning
channels:
  - conda-forge
dependencies:
  - python=3.6
  - nb_conda_kernels==2.1.0
  - ipywidgets
  # - tornado==4.5.3
  - pandas==0.23.4
  - scikit-learn==0.20.0
  - pip:
    - azure==4.0.0
    - azure-cli==2.0.44
    - prompt_toolkit==2.0.7
    - azureml-sdk[notebooks, automl]
    - lightgbm==2.1.2
    # - papermill==0.14.2
    # - git+https://github.com/theskumar/python-dotenv
