name: MLBatchAIHyperparameterTuning
channels:
  - conda-forge
dependencies:
  - python=3.5
  - pandas==0.23.4
  - scikit-learn==0.19.1
  - pip:
    - azure==4.0.0
    - azure-cli==2.0.44
    - lightgbm==2.1.2
